import React, { useState } from 'react';
import type { Recipe } from '../types';
import { BookmarkIcon, HeartIcon, TrashIcon, ClockIcon, UserGroupIcon, ShareIcon, DownloadIcon } from './Icon';

interface RecipeCardProps {
  recipe: Recipe;
  isSaved?: boolean;
  onSave?: (recipe: Recipe) => void;
  onDelete?: (recipeId: string) => void;
  onToggleFavorite?: (recipeId: string) => void;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, isSaved = false, onSave, onDelete, onToggleFavorite }) => {
  const [showCopied, setShowCopied] = useState(false);
  const [showDownloaded, setShowDownloaded] = useState(false);

  const handleSave = () => {
    if (onSave) {
      onSave(recipe);
    }
  };

  const handleDelete = () => {
    if (onDelete) {
      onDelete(recipe.id);
    }
  };

  const handleToggleFavorite = () => {
    if (onToggleFavorite) {
      onToggleFavorite(recipe.id);
    }
  };

  const handleDownload = () => {
    const recipeData = {
      recipeName: recipe.recipeName,
      description: recipe.description,
      ingredients: recipe.ingredients,
      instructions: recipe.instructions,
      prepTime: recipe.prepTime,
      cookTime: recipe.cookTime,
      servings: recipe.servings,
    };
    const dataStr = JSON.stringify(recipeData, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);

    const exportFileDefaultName = `${recipe.recipeName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.json`;

    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();

    setShowDownloaded(true);
    setTimeout(() => setShowDownloaded(false), 2000);
  };

  const handleShare = async () => {
    try {
    const jsonStr = JSON.stringify(recipe);
    // Encode to base64 with unicode support
    const base64 = btoa(encodeURIComponent(jsonStr).replace(/%([0-9A-F]{2})/g, (match, p1) => String.fromCharCode(parseInt(p1, 16))));
      const url = `${window.location.origin}${window.location.pathname}?share=${base64}`;
      const title = `Recipe: ${recipe.recipeName}`;
      const text = `Check out this delicious recipe for ${recipe.recipeName} generated by AI Personal Chef!`;
      
      if (navigator.share) {
        await navigator.share({
          title,
          text,
          url
        });
      } else {
        await navigator.clipboard.writeText(url);
        setShowCopied(true);
        setTimeout(() => setShowCopied(false), 2000);
      }
    } catch (err) {
      console.error('Failed to share:', err);
    }
  };

  return (
    <div className="bg-card rounded-2xl shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 flex flex-col group">
      <img src={`https://picsum.photos/400/300?random=${Math.floor(Math.random() * 1000)}&food`} alt={recipe.recipeName} className="w-full h-48 object-cover" onError={(e) => { e.currentTarget.src = 'https://via.placeholder.com/400x300/cccccc/000000?text=Recipe+Image'; }} />
      <div className="p-6 flex flex-col flex-grow">
        <div className="flex justify-between items-start mb-2">
          <h3 className="text-xl font-bold text-text-primary pr-2">{recipe.recipeName}</h3>
          <div className="flex items-center space-x-2 flex-shrink-0">
            <button onClick={handleShare} className="text-text-secondary hover:text-blue-500 transition-colors relative" title="Share Recipe">
              <ShareIcon />
              {showCopied && (
                <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 z-10">
                    <span className="block px-2 py-1 text-xs text-white bg-slate-800 rounded shadow-lg whitespace-nowrap animate-fade-in-up">
                    Link Copied!
                    </span>
                </div>
              )}
            </button>
            <button onClick={handleDownload} className="text-text-secondary hover:text-green-500 transition-colors relative" title="Download Recipe">
              <DownloadIcon />
              {showDownloaded && (
                <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 z-10">
                    <span className="block px-2 py-1 text-xs text-white bg-slate-800 rounded shadow-lg whitespace-nowrap animate-fade-in-up">
                    Downloaded!
                    </span>
                </div>
              )}
            </button>
            {isSaved && onToggleFavorite && (
              <button onClick={handleToggleFavorite} className={`text-red-500 hover:text-red-600 transition-colors ${recipe.isFavorite ? '' : 'text-opacity-40'}`} title={recipe.isFavorite ? "Remove from Favorites" : "Add to Favorites"}>
                <HeartIcon isFilled={recipe.isFavorite} />
              </button>
            )}
            {isSaved && onDelete && (
               <button onClick={handleDelete} className="text-text-secondary hover:text-red-500 transition-colors" title="Delete Recipe">
                <TrashIcon />
              </button>
            )}
             {!isSaved && onSave && (
              <button onClick={handleSave} className="text-secondary hover:text-emerald-600 transition-colors" title="Save Recipe">
                <BookmarkIcon />
              </button>
            )}
          </div>
        </div>
        <p className="text-text-secondary text-sm mb-4 flex-grow">{recipe.description}</p>
        
        <div className="flex items-center justify-around text-sm text-text-secondary border-t border-b border-slate-100 py-3 my-4">
            <div className="flex items-center space-x-2">
                <ClockIcon className="w-5 h-5 text-primary"/>
                <span>{recipe.prepTime}</span>
            </div>
            <div className="flex items-center space-x-2">
                <ClockIcon className="w-5 h-5 text-primary"/>
                <span>{recipe.cookTime}</span>
            </div>
            <div className="flex items-center space-x-2">
                <UserGroupIcon className="w-5 h-5 text-primary"/>
                <span>{recipe.servings}</span>
            </div>
        </div>

        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-md text-text-primary mb-2">Ingredients</h4>
            <ul className="list-disc list-inside space-y-1 text-sm text-text-secondary">
              {recipe.ingredients.map((ing, index) => <li key={index}>{ing}</li>)}
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-md text-text-primary mb-2">Instructions</h4>
            <ol className="list-decimal list-inside space-y-2 text-sm text-text-secondary">
              {recipe.instructions.map((step, index) => <li key={index}>{step}</li>)}
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecipeCard;